### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by mariusl** [djboni/librertos#1]
Hi 
Not an issue but more a request for some more examples please. 
Maybe to show the use of the message list and other features that can be seen in the code but might not be that clear on the usage.

Also the use of the software timers would be very helpful.

**Comment by djboni** [comment]
Hi,
Thank you for opening this issue.
I did not realize the timers were so poorly documented.
And examples are always good.
Now in the [doc/](https://github.com/djboni/librertos/tree/master/doc) directory there are Using_*.md files, which explain how to use the structures.
